export {default as NavBar} from './navbar/navbar'
export {default as Frontpage} from './frontpage/frontpage'
export {default as AboutMe} from './aboutme/aboutme'
export {default as Technology} from './technology/technology'
export {default as Projects} from './projects/projects'
export {default as Contact} from './contact/contact'
export {default as Footer} from './footer/footer'